apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data # Nom du PVC utilisé par le Deployment
spec:
  accessModes:
    - ReadWriteOnce # Accès en lecture/écriture par un seul nœud (adapté à Postgres)
  resources:
    requests:
      storage: 5Gi # Taille demandée pour le volume persistant
  storageClassName: exoscale-sbs # type de stockage du cluster k8s, exoscale-sbs par défaut sur SKS