apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: peppermint     # Nom d'utilisateur PostgreSQL utilisé par l'application
  POSTGRES_PASSWORD: "1234"     # Mot de passe en clair (exercice). En prod, utilisez un secret fort.
  POSTGRES_DB: peppermint       # Nom de la base de données initiale
# Utilisation :
# Dans le Deployment, remplacer les variables d'env par :
# envFrom:
#   - secretRef:
#       name: postgres-secret