apiVersion: v1
kind: Secret
metadata:
    name: peppermint-secret
type: Opaque
stringData:
    DB_USERNAME: peppermint       # Nom d'utilisateur PostgreSQL
    DB_PASSWORD: "1234"           # Mot de passe (exercice). En prod, utilisez un secret fort.
    DB_HOST: peppermint-postgres  # Service DNS interne pointant vers PostgreSQL
    SECRET: peppermint4life       # Secret applicatif (utilisé par Peppermint)